{% set name = "boxsdk" %}
{% set version = "3.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/boxsdk-{{ version }}.tar.gz
  sha256: c01350bdb0d24aa7927a64f6e9e8d7899be2ff43ea0e1410d4a1a273763146d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - attrs >=17.3.0
    - urllib3
    - requests >=2.4.3,<3
    - requests-toolbelt >=0.4.0
    - python-dateutil

test:
  imports:
    - boxsdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/box/box-python-sdk
  summary: Official Box Python SDK
  doc_url: https://pythonhosted.org/boxsdk/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
